library(shiny)
library(shinythemes)
library(shinyjs)
library(plotly)
library(shinydashboard)
library(httr)
library(jsonlite)
library(here)     
library(tidyverse)
library(yesno)
library(gt)
library(readxl)
library(postgresr)
options(dplyr.summarise.inform = FALSE)
country <- "Tanzania" # Tanzania, all
study <- "Optimisation"
source(here("Metabase Functions.R"))
source(here("Metabase ShinyApp.R"))
parentapp_shiny(country = country, study = study)
